### ISSUE TITLE
child-theme-settings.php wp_editor bug

### ISSUE THREAD

**Issue by EJOweb** [billerickson/BE-Genesis-Child#6]
The <b>wp_editor</b> in the <b>footer_metabox</b> isn't working as it should. It seems like the second argument, the editor_id, may only contain lower-case letters. Now it's like <i>child-settings[footer-left]</i>

https://codex.wordpress.org/Function_Reference/wp_editor

**Comment by Desouza13** [comment]
Hey Bill, 

May I ask why you are not using this as a base theme anymore? Have you created an updated base theme that you now use? 

Thanks a lot, 

Kevin

**Comment by billerickson** [comment]
I have an HTML5 base child theme that I use that's not public. It's very similar to this one but with the CSS targeting the HTML5 elements (copied Genesis' stylesheet then made it more similar to the stylesheet in this theme).
